# Generated by Django 5.1.4 on 2025-03-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='area',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='parking',
            field=models.IntegerField(default=1),
        ),
    ]
